import sqlite3
import pygame

display = pygame.display.set_mode((1200, 1000))

conn = sqlite3.connect('football_leagues.db')
cursor = conn.cursor()

cursor.execute('DROP TABLE players')
cursor.execute('DROP TABLE teams')

cursor.execute('''
CREATE TABLE IF NOT EXISTS countries (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL
)
''')

cursor.execute('''
CREATE TABLE IF NOT EXISTS teams (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    country_id INTEGER NOT NULL,
    budget INTEGER,
    FOREIGN KEY (country_id) REFERENCES countries(id)
)
''')

cursor.execute('''
CREATE TABLE IF NOT EXISTS players (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    rating INTEGER,
    picture TEXT,
    position TEXT,
    value INTEGER,
    is_starting TEXT,
    team_id INTEGER NOT NULL,
    FOREIGN KEY (team_id) REFERENCES teams(id)
)
''')

countries = ['England', 'Spain', 'Germany', 'France', 'Italy']
for country in countries:
    cursor.execute('INSERT OR IGNORE INTO countries (name) VALUES (?)', (country,))

teams_and_players = {
    'England': {
        'Manchester United': {'David de Gea': [87, 'picture/De_Gea.jpg', 'GK', 60, True],
                              'Aaron Wan-Bissaka': [83, 'picture/Wan_Bissaka_New.jpg', 'DEF', 35, True],
                              'Harry Maguire': [84, 'picture/Maguire.jpg', 'DEF', 37.5, True],
                              'Victor Lindelof': [80, 'picture/Lindelof.jpg', 'DEF', 20, True],
                              'Luke Shaw': [84, 'picture/Luke_Shaw.jpg', 'DEF', 32, True],
                              'Scott McTominay': [82, 'picture/McTominay.jpg', 'MID', 28, True],
                              'Bruno Fernandes': [88, 'picture/Bruno_Fernandes.jpg', 'MID', 75, True],
                              'Paul Pogba': [87, 'picture/Paul_Pogba.jpg', 'MID', 82.5, True],
                              'Marcus Rashford': [85, 'picture/Marcus_Rashford.jpg', 'ATK', 60, True],
                              'Ramsus Hojlund': [89, 'picture/Rasmus_Hojlund.jpg', 'ATK', 85, True],
                              'Jadon Sancho': [87, 'picture/Jadon_Sancho.jpg', 'ATK', 65, True],
                              'Nemanja Matic': [81, 'picture/Nemanja_Matic.jpg', 'MID', 30, False],
                              'Juan Mata': [81, 'picture/Juan_Mata.jpg', 'MID', 25, False],
                              'Antony Martial': [82, 'picture/Martial.jpg', 'ATK', 30, False],
                              'Fred': [80, 'picture/Fred.jpg', 'MID', 28, False],
                              'Jesse Lingard': [80, 'picture/Lingard.jpg', 'MID', 24, False]},
        'Liverpool': {'Alisson Becker': [89, 'picture/Alisson_Becker.jpg', 'GK', 50, True],
                      'Trent Alexander-Arnold': [87, 'picture/Trent_Alexander-Arnold.jpg', 'DEF', 75, True],
                      'Virgil van Dijk': [90, 'picture/Virgil_van_Dijk.jpg', 'DEF', 80, True],
                      'Joel Matip': [83, 'picture/Joel_Matip.jpg', 'DEF', 20, True],
                      'Andy Robertson': [87, 'picture/Andrew_Robertson.jpg', 'DEF', 45, True],
                      'Fabinho': [86, 'picture/Fabinho.jpg', 'MID', 50, True],
                      'Jordan Henderson': [84, 'picture/Jordan_Henderson.jpg', 'MID', 23, True],
                      'Thiago Alcantara': [85, 'picture/Thiago_Alcantara.jpg', 'MID', 30, True],
                      'Diogo Jota': [83, 'picture/Diogo_Jota.jpg', 'ATK', 30, True],
                      'Roberto Firmino': [85, 'picture/Roberto_Firmino.jpg', 'ATK', 55, True],
                      'Sadio Mane': [89, 'picture/Sadio_Mane.jpg', 'ATK', 80, True],
                      'James Milner': [81, 'picture/milner.jpg', 'MID', 13, False],
                      'Keita': [79, 'picture/keita.jpg', 'MID', 12, False],
                      'Oxlade-Chamberlain': [82, 'picture/chamberlain.jpg', 'MID', 20, False],
                      'Dejan Lovren': [80, 'picture/dejan_lovren.jpg', 'DEF', 20, False],
                      'Georgino Wijnaldum': [87, 'picture/wijnaldum.jpg', 'MID', 56, False]},
        'Manchester City': {'Ederson': [88, 'picture/Ederson.jpg', 'GK', 70, True],
                            'Kyle Walker': [84, 'picture/Kyle_Walker.jpg', 'DEF', 30, True],
                            'Ruben Dias': [88, 'picture/Ruben_Dias.jpg', 'DEF', 65, True],
                            'John Stones': [89, 'picture/John_Stones.jpg', 'DEF', 70, True],
                            'Joao Cancelo': [86, 'picture/Joao_Cancelo.jpg', 'DEF', 50, True],
                            'Rodri': [87, 'picture/Rodri.jpg', 'MID', 60, True],
                            'Kevin De Bruyne': [91, 'picture/Kevin_De_Bruyne.jpg', 'MID', 110, True],
                            'Ilkay Gundogan': [87, 'picture/gundogan.jpg', 'MID', 70, True],
                            'Bernardo Silva': [87, 'picture/Bernardo_Silva.jpg', 'ATK', 70, True],
                            'Gabriel Jesus': [88, 'picture/Gabriel_Jesus.jpg', 'ATK', 72, True],
                            'Raheem Sterling': [88, 'picture/Raheem_Sterling.jpg', 'ATK', 72, True],
                            'Phil Foden': [84, 'picture/Phil_Foden.jpg', 'ATK', 45, False],
                            'Fernadinho': [87, 'picture/fernandinho.jpg', 'MID', 75, False],
                            'David Silva': [90, 'picture/david_silva.jpg', 'ATK', 105, False],
                            'Leroy Sane': [86, 'picture/leroy_sane.jpg', 'ATK', 60, False],
                            'Sergeo Kun Aguero': [91, 'picture/sergio_aguero.jpg', 'ATK', 120, False]},
        'Chelsea': {'Edouard Mendy': [89, 'picture/Edouard_Mendy.jpg', 'GK', 90, True],
                    'Reece James': [84, 'picture/Reece_James.jpg', 'DEF', 40, True],
                    'Thiago Silva': [85, 'picture/Thiago_Silva.jpg', 'DEF', 45, True],
                    'Antonio Rudiger': [83, 'picture/Antonio_Rudiger.jpg', 'DEF', 30, True],
                    'Marcos Alonso': [81, 'picture/Marcos_Alonso.jpg', 'DEF', 15, True],
                    'Jorginho': [85, 'picture/Jorginho.jpg', 'MID', 40, True],
                    'N’Golo Kante': [89, 'picture/NGolo_Kante.jpg', 'MID', 95, True],
                    'Mason Mount': [84, 'picture/Mason_Mount.jpg', 'MID', 35, True],
                    'Kai Havertz': [84, 'picture/Kai_Havertz.jpg', 'ATK', 35, True],
                    'Romelu Lukaku': [85, 'picture/Romelu_Lukaku.jpg', 'ATK', 45, True],
                    'Christian Pulisic': [82, 'picture/Christian_Pulisic.jpg', 'ATK', 23, True],
                    'Willian': [87, 'picture/willian.jpg', 'ATK', 80, False],
                    'Tammy Abraham': [83, 'picture/abraham.jpg', 'ATK', 30, False],
                    'Mateo Kovacic': [86, 'picture/kovacic.jpg', 'MID', 50, False],
                    'Kepa Arrizabalaga': [84, 'picture/kepa.jpg', 'GK', 40, False],
                    'Michy Batshuayi': [87, 'picture/batshuayi.jpg', 'ATK', 45, False]},
        'Arsenal': {'Bernd Leno': [84, 'picture/Bernd_Leno.jpg', 'GK', 30, True],
                    'Takehiro Tomiyasu': [79, 'picture/Takehiro_Tomiyasu.jpg', 'DEF', 9, True],
                    'Ben White': [89, 'picture/Ben_White.jpg', 'DEF', 85, True],
                    'Gabriel Magalhaes': [80, 'picture/Gabriel_Magalhaes.jpg', 'DEF', 12, True],
                    'Kieran Tierney': [80, 'picture/Kieran_Tierney.jpg', 'DEF', 12, True],
                    'Thomas Partey': [83, 'picture/Thomas_Partey.jpg', 'MID', 25, True],
                    'Granit Xhaka': [80, 'picture/Granit_Xhaka.jpg', 'MID', 18, True],
                    'Emile Smith Rowe': [80, 'picture/Emile_Smith_Rowe.jpg', 'MID', 12, True],
                    'Gabriel Martinelli': [78, 'picture/Gabriel_Martinelli.jpg', 'ATK', 8, True],
                    'Pierre-Emerick Aubameyang': [85, 'picture/Pierre-Emerick_Aubameyang.jpg', 'ATK', 65, True],
                    'Bukayo Saka': [82, 'picture/Bukayo_Saka.jpg', 'ATK', 25, True],
                    'Mesut Ozil': [90, 'picture/ozil.jpg', 'ATK', 102, False],
                    'Alexandre Lacazette': [87, 'picture/lacazette.jpg', 'ATK', 80, False],
                    'Henrikh Mkhitaryan': [86, 'picture/mkhitaryan.jpg', 'MID', 55, False],
                    'Matteo Guendouzi': [77, 'picture/guendouzi.jpg', 'MID', 3, False],
                    'Konstantinos Mavropanos': [78, 'picture/mavropanos.jpg', 'DEF', 4, False]},
        'Tottenham Hotspur': {'Hugo Lloris': [87, 'picture/Hugo_Lloris.jpg', 'GK', 55, True],
                              'Emerson Royal': [78, 'picture/Emerson_Royal.jpg', 'DEF', 4, True],
                              'Cristian Romero': [82, 'picture/Cristian_Romero.jpg', 'DEF', 25, True],
                              'Eric Dier': [78, 'picture/Eric_Dier.jpg', 'DEF', 8, True],
                              'Sergio Reguilon': [83, 'picture/Sergio_Reguilon.jpg', 'DEF', 25, True],
                              'Pierre-Emile Hojbjerg': [82, 'picture/Pierre-Emile_Hojbjerg.jpg', 'MID', 23, True],
                              'Oliver Skipp': [76, 'picture/Oliver_Skipp.jpg', 'MID', 3, True],
                              'Dele Alli': [80, 'picture/Dele_Alli.jpg', 'MID', 30, True],
                              'Heung-Min Son': [89, 'picture/Heung-Min_Son.jpg', 'ATK', 90, True],
                              'Harry Kane': [90, 'picture/Harry_Kane.jpg', 'ATK', 110, True],
                              'Lucas Moura': [81, 'picture/Lucas_Moura.jpg', 'ATK', 25, True],
                              'Christian Eriksen': [87, ]},
        # 'Leicester City': {'Kasper Schmeichel': [84, 'picture/Kasper_Schmeichel.jpg'],
        #                    'Timothy Castagne': [79, 'picture/Timothy_Castagne.jpg'],
        #                    'Jonny Evans': [80, 'picture/Jonny_Evans.jpg'],
        #                    'Caglar Soyuncu': [80, 'picture/Caglar_Soyuncu.jpg'],
        #                    'Luke Thomas': [76, 'picture/Luke_Thomas.jpg'],
        #                    'Wilfred Ndidi': [86, 'picture/Wilfred_Ndidi.jpg'],
        #                    'Youri Tielemans': [84, 'picture/Youri_Tielemans.jpg'],
        #                    'James Maddison': [84, 'picture/James_Maddison.jpg'],
        #                    'Harvey Barnes': [81, 'picture/Harvey_Barnes.jpg'],
        #                    'Jamie Vardy': [86, 'picture/Jamie_Vardy.jpg'],
        #                    'Kelechi Iheanacho': [78, 'picture/Kelechi_Iheanacho_New.jpg']},
        # 'West Ham United': {'Lukasz Fabianski': [81, 'picture/Lukasz_Fabianski.jpg'],
        #                     'Vladimir Coufal': [78, 'picture/Vladimir_Coufal.jpg'],
        #                     'Angelo Ogbonna': [80, 'picture/Angelo_Ogbonna.jpg'],
        #                     'Kurt Zouma': [80, 'picture/Kurt_Zouma.jpg'],
        #                     'Aaron Cresswell': [78, 'picture/Aaron_Cresswell.jpg'],
        #                     'Declan Rice': [83, 'picture/Declan_Rice.jpg'],
        #                     'Tomas Soucek': [82, 'picture/Tomas_Soucek.jpg'],
        #                     'Pablo Fornals': [80, 'picture/Pablo_Fornals.jpg'],
        #                     'Said Benrahma': [79, 'picture/Said_Benrahma.jpg'],
        #                     'Michail Antonio': [79, 'picture/Michail_Antonio.jpg'],
        #                     'Jarrod Bowen': [83, 'picture/Jarrod_Bowen.jpg']},
        # 'Everton': {'Jordan Pickford': [82, 'picture/Jordan_Pickford_2.jpg'],
        #             'Seamus Coleman': [80, 'picture/Seamus_Coleman.jpg'],
        #             'Michael Keane': [78, 'picture/Michael_Keane_New.jpg'],
        #             'Ben Godfrey': [77, 'picture/Ben_Godfrey.jpg'], 'Lucas Digne': [84, 'picture/Lucas_Digne.jpg'],
        #             'Abdoulaye Doucoure': [80, 'picture/Abdoulaye_Doucoure.jpg'], 'Allan': [83, 'picture/Allan.jpg'],
        #             'Andros Townsend': [77, 'picture/Andros_Townsend.jpg'],
        #             'Demarai Gray': [78, 'picture/Demarai_Gray.jpg'], 'Richarlison': [82, 'picture/Richarlison.jpg'],
        #             'Dominic Calvert-Lewin': [81, 'picture/Dominic_Calvert_Lewin.jpg']},
        # 'Aston Villa': {'Emiliano Martinez': [84, 'picture/Emiliano_Martinez.jpg'],
        #                 'Matty Cash': [79, 'picture/Matty_Cash.jpg'], 'Ezri Konsa': [78, 'picture/Ezri_Konsa.jpg'],
        #                 'Tyrone Mings': [78, 'picture/Tyrone_Mings.jpg'],
        #                 'Matt Targett': [78, 'picture/Matt_Targett.jpg'],
        #                 'John McGinn': [80, 'picture/John_McGinn.jpg'],
        #                 'Douglas Luiz': [79, 'picture/Douglas_Luiz.jpg'],
        #                 'Emiliano Buendia': [81, 'picture/Emiliano_Buendia.jpg'],
        #                 'Leon Bailey': [82, 'picture/Leon_Bailey.jpg'],
        #                 'Ollie Watkins': [81, 'picture/Ollie_Watkins.jpg'],
        #                 'Danny Ings': [81, 'picture/Danny_Ings.jpg']},
        # 'Leeds United': {'Illan Meslier': [78, 'picture/Illan_Meslier.jpg'],
        #                  'Luke Ayling': [77, 'picture/Luke_Ayling.jpg'],
        #                  'Diego Llorente': [78, 'picture/Diego_Llorente.jpg'],
        #                  'Liam Cooper': [76, 'picture/Liam_Cooper.jpg'],
        #                  'Stuart Dallas': [78, 'picture/Stuart_Dallas.jpg'],
        #                  'Kalvin Phillips': [81, 'picture/Kalvin_Phillips.jpg'],
        #                  'Mateusz Klich': [76, 'picture/Mateusz_Klich.jpg'], 'Raphinha': [83, 'picture/Raphinha.jpg'],
        #                  'Rodrigo': [80, 'picture/Rodrigo.jpg'], 'Jack Harrison': [78, 'picture/Jack_Harrison.jpg'],
        #                  'Patrick Bamford': [78, 'picture/Patrick_Bamford.jpg']},
        # 'Wolverhampton Wanderers': {'Jose Sa': [81, 'picture/Jose_Sa.jpg'],
        #                             'Nelson Semedo': [80, 'picture/Nelson_Semedo.jpg'],
        #                             'Conor Coady': [81, 'picture/Conor_Coady.jpg'],
        #                             'Max Kilman': [78, 'picture/Max_Kilman.jpg'],
        #                             'Romain Saiss': [79, 'picture/Romain_Saiss.jpg'],
        #                             'Joao Moutinho': [81, 'picture/Joao_Moutinho.jpg'],
        #                             'Ruben Neves': [81, 'picture/Ruben_Neves.jpg'],
        #                             'Adama Traore': [81, 'picture/Adama_Traore.jpg'],
        #                             'Daniel Podence': [78, 'picture/Daniel_Podence.jpg'],
        #                             'Francisco Trincao': [78, 'picture/Francisco_Trincao.jpg'],
        #                             'Raul Jimenez': [82, 'picture/Raul_Jimenez.jpg']},
        # 'Newcastle United': {'Martin Dubravka': [82, 'picture/Martin_Dubravka.jpg'],
        #                      'Javier Manquillo': [75, 'picture/Javier_Manquillo.jpg'],
        #                      'Fabian Schar': [78, 'picture/Fabian_Schar.jpg'],
        #                      'Jamaal Lascelles': [76, 'picture/Jamaal_Lascelles.jpg'],
        #                      'Jamal Lewis': [75, 'picture/Jamal_Lewis.jpg'],
        #                      'Jonjo Shelvey': [76, 'picture/Jonjo_Shelvey.jpg'],
        #                      'Isaac Hayden': [76, 'picture/Isaac_Hayden.jpg'],
        #                      'Miguel Almiron': [78, 'picture/Miguel_Almiron.jpg'],
        #                      'Allan Saint-Maximin': [81, 'picture/Allan_Saint_Maximin.jpg'],
        #                      'Callum Wilson': [79, 'picture/Callum_Wilson.jpg'],
        #                      'Joelinton': [75, 'picture/Joelinton.jpg']},
    #     'Crystal Palace': ['Vicente Guaita', 'Joel Ward', 'Joachim Andersen', 'Marc Guehi', 'Tyrick Mitchell',
    #                        'James McArthur', 'Conor Gallagher', 'Cheikhou Kouyate', 'Jordan Ayew', 'Wilfried Zaha',
    #                        'Christian Benteke'],
    #     'Southampton': ['Alex McCarthy', 'Tino Livramento', 'Jan Bednarek', 'Mohammed Salisu', 'Kyle Walker-Peters',
    #                     'Oriol Romeu', 'James Ward-Prowse', 'Stuart Armstrong', 'Nathan Redmond', 'Che Adams',
    #                     'Adam Armstrong'],
    #     'Burnley': ['Nick Pope', 'Matthew Lowton', 'James Tarkowski', 'Ben Mee', 'Charlie Taylor',
    #                 'Josh Brownhileverley', 'Moussa Sissoko', 'Juraj Kucka', 'Ismaila Sarr', 'Emmanuel Dennis',
    #                 'Joshua King'],
    #     'Norwich City': ['Tim Krul', 'Max Aarons', 'Ben Gibson', 'Grant Hanley', 'Brandon Williams', 'Kenny McLean',
    #                      'Billy Gilmour', 'Todd Cantwell', 'Kieran Dowell', 'Teemu Pukki', 'Milot Rashica'],
    #     'Brentford': ['David Raya', 'Sergi Canos', 'Pontus Jansson', 'Ethan Pinnock', 'Rl', 'Ashley Westwood',
    #                   'Dwight McNeil', 'Johann Berg Gudmundsson', 'Chris Wood', 'Jay Rodriguez'],
    #     'Watford': ['Ben Foster', 'Kiko Femenia', 'Craig Cathcart', 'William Troost-Ekong', 'Danny Rose',
    #                 'Tom Clico Henry', 'Christian Norgaard', 'Vitaly Janelt', 'Mathias Jensen', 'Bryan Mbeumo',
    #                 'Ivan Toney', 'Saman Ghoddos']
    # },
    # 'Spain': {
    #     'Real Madrid': ['Thibaut Courtois', 'Daniel Carvajal', 'Eder Militao', 'David Alaba', 'Ferland Mendy',
    #                     'Casemiro', 'Luka Modric', 'Toni Kroos', 'Karim Benzema', 'Vinicius Junior', 'Rodrygo'],
    #     'Barcelona': ['Marc-Andre ter Stegen', 'Sergi Roberto', 'Gerard Pique', 'Ronald Araujo', 'Jordi Alba',
    #                   'Sergio Busquets', 'Frenkie de Jong', 'Pedri', 'Ousmane Dembele', 'Memphis Depay',
    #                   'Ferran Torres'],
    #     'Atletico Madrid': ['Jan Oblak', 'Kieran Trippier', 'Stefan Savic', 'Jose Gimenez', 'Renan Lodi',
    #                         'Marcos Llorente', 'Koke', 'Thomas Lemar', 'Angel Correa', 'Luis Suarez', 'Joao Felix'],
    #     'Sevilla': ['Yassine Bounou', 'Jesus Navas', 'Jules Kounde', 'Diego Carlos', 'Marcos Acuna', 'Fernando',
    #                 'Joan Jordan', 'Ivan Rakitic', 'Suso', 'Lucas Ocampos', 'Youssef En-Nesyri'],
    #     'Real Sociedad': ['Alex Remiro', 'Joseba Zaldua', 'Aritz Elustondo', 'Robin Le Normand', 'Nacho Monreal',
    #                       'Martin Zubimendi', 'Mikel Merino', 'David Silva', 'Adnan Januzaj', 'Mikel Oyarzabal',
    #                       'Alexander Isak'],
    #     'Villarreal': ['Geronimo Rulli', 'Juan Foyth', 'Raul Albiol', 'Pau Torres', 'Alfonso Pedraza', 'Dani Parejo',
    #                    'Etienne Capoue', 'Manu Trigueros', 'Gerard Moreno', 'Paco Alcacer', 'Samuel Chukwueze'],
    #     'Real Betis': ['Claudio Bravo', 'Hector Bellerin', 'German Pezzella', 'Marc Bartra', 'Alex Moreno',
    #                    'Guido Rodriguez', 'Sergio Canales', 'Nabil Fekir', 'Juanmi', 'Borja Iglesias',
    #                    'Cristian Tello'],
    #     'Athletic Bilbao': ['Unai Simon', 'Oscar de Marcos', 'Yeray Alvarez', 'Inigo Martinez', 'Yuri Berchiche',
    #                         'Unai Vencedor', 'Dani Garcia', 'Iker Muniain', 'Alex Berenguer', 'Inaki Williams',
    #                         'Raul Garcia'],
    #     'Celta Vigo': ['Matias Dituro', 'Hugo Mallo', 'Nestor Araujo', 'Jeison Murillo', 'Javi Galan', 'Renato Tapia',
    #                    'Brais Mendez', 'Denis Suarez', 'Franco Cervi', 'Iago Aspas', 'Santi Mina'],
    #     'Valencia': ['Jasper Cillessen', 'Jose Gaya', 'Gabriel Paulista', 'Omar Alderete', 'Thierry Correia',
    #                  'Carlos Soler', 'Hugo Guillamon', 'Uros Racic', 'Goncalo Guedes', 'Maxi Gomez', 'Denis Cheryshev'],
    #     'Espanyol': ['Diego Lopez', 'Oscar Gil', 'Leandro Cabrera', 'Sergi Gomez', 'Adria Pedrosa', 'Sergi Darder',
    #                  'Keidi Bare', 'Adrian Embarba', 'Oscar Melendo', 'Raul de Tomas', 'Wu Lei'],
    #     'Getafe': ['David Soria', 'Damian Suarez', 'Jorge Cuenca', 'Stefan Mitrovic', 'Mathias Olivera',
    #                'Mauro Arambarri', 'Nemanja Maksimovic', 'Carles Alena', 'Jakub Jankto', 'Enes Unal', 'Jaime Mata'],
    #     'Granada': ['Luis Maximiano', 'Quini', 'German Sanchez', 'Domingos Duarte', 'Carlos Neva', 'Maxime Gonalons',
    #                 'Luis Milla', 'Ruben Rochina', 'Darwin Machis', 'Jorge Molina', 'Luis Suarez'],
    #     'Elche': ['Edgar Badia', 'Helibelton Palacios', 'Enzo Roco', 'Diego Gonzalez', 'Johan Mojica', 'Ivan Marcone',
    #               'Gerard Gumbau', 'Fidel', 'Pere Milla', 'Lucas Boye', 'Javier Pastore'],
    #     'Osasuna': ['Sergio Herrera', 'Nacho Vidal', 'David Garcia', 'Aridane Hernandez', 'Juan Cruz', 'Lucas Torro',
    #                 'Jon Moncayola', 'Ruben Garcia', 'Kike Barja', 'Chimy Avila', 'Kike Garcia'],
    #     'Mallorca': ['Manolo Reina', 'Pablo Maffeo', 'Martin Valjent', 'Franco Russo', 'Jaume Costa', 'Iddrisu Baba',
    #                  'Salva Sevilla', 'Kang-in Lee', 'Takefusa Kubo', 'Dani Rodriguez', 'Abdon Prats'],
    #     'Alaves': ['Fernando Pacheco', 'Ximo Navarro', 'Victor Laguardia', 'Florian Lejeune', 'Ruben Duarte',
    #                'Mamadou Loum', 'Tomas Pina', 'Edgar Mendez', 'Pere Pons', 'Joselu', 'Luis Rioja'],
    #     'Cadiz': ['Jeremias Ledesma', 'Iza Carcelen', 'Juan Cala', 'Fali', 'Alfonso Espino', 'Jens Jonsson',
    #               'Fede San Emeterio', 'Salvi Sanchez', 'Alex Fernandez', 'Alvaro Negredo', 'Anthony Lozano'],
    #     'Rayo Vallecano': ['Stole Dimitrievski', 'Ivan Balliu', 'Alejandro Catena', 'Esteban Saveljich', 'Fran Garcia',
    #                        'Oscar Valentin', 'Santi Comesana', 'Isi Palazon', 'Alvaro Garcia', 'Randy Nteka',
    #                        'Radamel Falcao'],
    #     'Levante': ['Aitor Fernandez', 'Son', 'Rober Pier', 'Oscar Duarte', 'Carlos Clerc', 'Jose Campana',
    #                 'Nemanja Radoja', 'Gonzalo Melero', 'Jorge de Frutos', 'Roger Marti', 'Jose Luis Morales']
    # },
    # 'France': {
    #     'Paris Saint-Germain': ['Gianluigi Donnarumma', 'Achraf Hakimi', 'Marquinhos', 'Presnel Kimpembe',
    #                             'Nuno Mendes', 'Leandro Paredes', 'Marco Verratti', 'Georginio Wijnaldum',
    #                             'Lionel Messi', 'Kylian Mbappe', 'Neymar'],
    #     'Marseille': ['Steve Mandanda', 'Pol Lirola', 'William Saliba', 'Duje Caleta-Car', 'Luan Peres',
    #                   'Valentin Rongier', 'Boubacar Kamara', 'Dimitri Payet', 'Cengiz Under', 'Arkadiusz Milik',
    #                   'Konrad de la Fuente'],
    #     'Lyon': ['Anthony Lopes', 'Leo Dubois', 'Jason Denayer', 'Jerome Boateng', 'Emerson Palmieri',
    #              'Bruno Guimaraes', 'Houssem Aouar', 'Lucas Paqueta', 'Karl Toko Ekambi', 'Moussa Dembele',
    #              'Xherdan Shaqiri'],
    #     'Monaco': ['Alexander Nubel', 'Ruben Aguilar', 'Axel Disasi', 'Benoit Badiashile', 'Caio Henrique',
    #                'Aurelien Tchouameni', 'Youssouf Fofana', 'Gelson Martins', 'Aleksandr Golovin', 'Kevin Volland',
    #                'Wissam Ben Yedder'],
    #     'Rennes': ['Alfred Gomis', 'Hamari Traore', 'Nayef Aguerd', 'Warmed Omari', 'Birger Meling', 'Flavien Tait',
    #                'Baptiste Santamaria', 'Lovro Majer', 'Benjamin Bourigeaud', 'Martin Terrier', 'Gaetan Laborde'],
    #     'Lille': ['Ivo Grbic', 'Zeki Celik', 'Jose Fonte', 'Sven Botman', 'Reinildo Mandava', 'Benjamin Andre', 'Xeka',
    #               'Jonathan Ikone', 'Jonathan Bamba', 'Burak Yilmaz', 'Jonathan David'],
    #     'Nice': ['Walter Benitez', 'Jordan Lotomba', 'Jean-Clair Todibo', 'Dante', 'Melvin Bard', 'Pablo Rosario',
    #              'Mario Lemina', 'Calvin Stengs', 'Kasper Dolberg', 'Amine Gouiri', 'Justin Kluivert'],
    #     'Lens': ['Jean-Louis Leca', 'Jonathan Gradit', 'Kevin Danso', 'Facundo Medina', 'Jonathan Clauss',
    #              'Seko Fofana', 'Yannick Cahuzac', 'Przemyslaw Frankowski', 'Gael Kakuta', 'Florian Sotoca',
    #              'Ignatius Ganago'],
    #     'Strasbourg': ['Matz Sels', 'Frederic Guilbert', 'Alexander Djiku', 'Gerzino Nyamsi', 'Anthony Caci',
    #                    'Jeanricner Bellegarde', 'Sanjin Prcic', 'Adrien Thomasson', 'Ludovic Ajorque', 'Habib Diallo',
    #                    'Kevin Gameiro'],
    #     'Angers': ['Paul Bernardoni', 'Vincent Manceau', 'Ismael Traore', 'Romain Thomas', 'Souleyman Doumbia',
    #                'Thomas Mangani', 'Nabil Bentaleb', 'Angelo Fulgini', 'Sofiane Boufal', 'Mohamed-Ali Cho',
    #                'Stephane Bahoken'],
    #     'Montpellier': ['Jonas Omlin', 'Arnaud Souquet', 'Matheus Thuler', 'Mamadou Sakho', 'Mihailo Ristic',
    #                     'Jordan Ferri', 'Joris Chotard', 'Teji Savanier', 'Stephy Mavididi', 'Valere Germain',
    #                     'Elye Wahi'],
    #     'Reims': ['Predrag Rajkovic', 'Thomas Foket', 'Wout Faes', 'Yunis Abdelhamid', 'Konan', 'Marshall Munetsi',
    #               'Moreto Cassama', 'Ilan Kebbal', 'Mathieu Cafaro', 'El Bilal Toure', 'Boulaye Dia'],
    #     'Brest': ['Gautier Larsonneur', 'Ronael Pierre-Gabriel', 'Brendan Chardonnet', 'Christophe Herelle',
    #               'Jere Uronen', 'Haris Belkebla', 'Paul Lasne', 'Romain Faivre', 'Franck Honorat', 'Steve Mounie',
    #               'Irvin Cardona'],
    #     'Bordeaux': ['Benoit Costil', 'Enock Kwateng', 'Laurent Koscielny', 'Mexer', 'Loris Benito', 'Otavio',
    #                  'Toma Basic', 'Yacine Adli', 'Remi Oudin', 'Hwang Ui-jo', 'Samuel Kalu'],
    #     'Nantes': ['Alban Lafont', 'Dennis Appiah', 'Andrei Girotto', 'Nicolas Pallois', 'Charles Traore',
    #                'Pedro Chirivella', 'Mehdi Abeid', 'Ludovic Blas', 'Randal Kolo Muani', 'Moses Simon',
    #                'Kalifa Coulibaly'],
    #     'Troyes': ['Gauthier Gallon', 'Issa Kabore', 'Jimmy Giraudon', 'Yoann Salmier', 'Giulian Biancone',
    #                'Rominigue Kouame', 'Florian Tardieu', 'Xavier Chavalerin', 'Tristan Dingome', 'Mama Balde',
    #                'Yoann Touzghar'],
    #     'Metz': ['Alexandre Oukidja', 'Fabien Centonze', 'Dylan Bronn', 'Boubakar Kouyate', 'Thomas Delaine',
    #              'Habib Maiga', 'Pape Sarr', 'Farid Boulaya', 'Opa Nguette', 'Ibrahima Niane', 'Papa Yade'],
    #     'Clermont': ['Arthur Desmas', 'Akim Zedadka', 'Cedric Hountondji', 'Florent Ogier', 'Vital Nsimba',
    #                  'Johan Gastien', 'Jason Berthomier', 'Yohann Magnin', 'Jodel Dossou', 'Mohamed Bayo',
    #                  'Jim Allevinah'],
    #     'Saint-Etienne': ['Etienne Green', 'Mathieu Debuchy', 'Harold Moukoudi', 'Timothee Kolodziejczak',
    #                       'Miguel Trauco', 'Mahdi Camara', 'Yvan Neyou', 'Romain Hamouma', 'Denis Bouanga',
    #                       'Arnaud Nordin', 'Wahbi Khazri'],
    #     'Lorient': ['Paul Nardi', 'Houboulang Mendes', 'Julien Laporte', 'Andreaw Gravillon', 'Vincent Le Goff',
    #                 'Laurent Abergel', 'Fabien Lemoine', 'Enzo Le Fee', 'Yoane Wissa', 'Armand Lauriente',
    #                 'Terem Moffi']
    # },
    # 'Germany': {
    #     'Bayern Munich': ['Manuel Neuer', 'Benjamin Pavard', 'Dayot Upamecano', 'Lucas Hernandez', 'Alphonso Davies',
    #                       'Joshua Kimmich', 'Leon Goretzka', 'Thomas Muller', 'Leroy Sane', 'Robert Lewandowski',
    #                       'Kingsley Coman'],
    #     'Borussia Dortmund': ['Gregor Kobel', 'Thomas Meunier', 'Mats Hummels', 'Manuel Akanji', 'Raphael Guerreiro',
    #                           'Axel Witsel', 'Jude Bellingham', 'Marco Reus', 'Julian Brandt', 'Erling Haaland',
    #                           'Donyell Malen'],
    #     'RB Leipzig': ['Peter Gulacsi', 'Nordi Mukiele', 'Willi Orban', 'Josko Gvardiol', 'Angelino', 'Kevin Kampl',
    #                    'Tyler Adams', 'Christopher Nkunku', 'Dani Olmo', 'Emil Forsberg', 'Andre Silva'],
    #     'Bayer Leverkusen': ['Lukáš Hrádecký', 'Jeremie Frimpong', 'Jonathan Tah', 'Edmond Tapsoba', 'Mitchell Bakker',
    #                          'Kerem Demirbay', 'Charles Aranguiz', 'Moussa Diaby', 'Florian Wirtz', 'Paulinho',
    #                          'Patrik Schick'],
    #     'Eintracht Frankfurt': ['Kevin Trapp', 'Danny da Costa', 'Martin Hinteregger', 'Evan N\'Dicka', 'Filip Kostić',
    #                             'Djibril Sow', 'Sebastian Rode', 'Daichi Kamada', 'Jesper Lindstrøm', 'Rafael Borré',
    #                             'Gonçalo Paciência'],
    #     'Borussia Monchengladbach': ['Yann Sommer', 'Stefan Lainer', 'Matthias Ginter', 'Nico Elvedi',
    #                                  'Ramy Bensebaini', 'Denis Zakaria', 'Florian Neuhaus', 'Jonas Hofmann',
    #                                  'Lars Stindl', 'Alassane Pléa', 'Marcus Thuram'],
    #     'VfL Wolfsburg': ['Koen Casteels', 'Kevin Mbabu', 'Maxence Lacroix', 'John Brooks', 'Paulo Otavio',
    #                       'Maximilian Arnold', 'Xaver Schlager', 'Josip Brekalo', 'Renato Steffen', 'Wout Weghorst',
    #                       'Lukas Nmecha'],
    #     'Hertha BSC': ['Alexander Schwolow', 'Dedryck Boyata', 'Niklas Stark', 'Jordan Torunarigha',
    #                    'Marvin Plattenhardt', 'Lucas Tousart', 'Santiago Ascacibar', 'Matheus Cunha', 'Vladimír Darida',
    #                    'Dodi Lukebakio', 'Krzysztof Piątek'],
    #     'SC Freiburg': ['Mark Flekken', 'Jonathan Schmid', 'Philipp Lienhart', 'Manuel Gulde', 'Christian Günter',
    #                     'Maximilian Eggestein', 'Nicolas Höfler', 'Vincenzo Grifo', 'Woo-yeong Jeong', 'Roland Sallai',
    #                     'Lucas Höler'],
    #     'VfB Stuttgart': ['Florian Müller', 'Konstantinos Mavropanos', 'Waldemar Anton', 'Marc Oliver Kempf',
    #                       'Borna Sosa', 'Atakan Karazor', 'Orel Mangala', 'Philipp Förster', 'Chris Führich',
    #                       'Omar Marmoush', 'Sasa Kalajdzic'],
    #     '1. FSV Mainz 05': ['Robin Zentner', 'Jeremiah St. Juste', 'Moussa Niakhaté', 'Stefan Bell', 'Silvan Widmer',
    #                         'Leandro Barreiro', 'Jean-Paul Boëtius', 'Dominik Kohr', 'Jae-sung Lee', 'Karim Onisiwo',
    #                         'Jonathan Burkardt'],
    #     '1899 Hoffenheim': ['Oliver Baumann', 'Kevin Akpoguma', 'Stefan Posch', 'Chris Richards', 'David Raum',
    #                         'Diadie Samassekou', 'Sebastian Rudy', 'Andrej Kramaric', 'Munas Dabbur',
    #                         'Christoph Baumgartner', 'Ihlas Bebou'],
    #     'FC Augsburg': ['Rafal Gikiewicz', 'Robert Gumny', 'Jeffrey Gouweleeuw', 'Felix Uduokhai', 'Iago',
    #                     'Carlos Gruezo', 'Rani Khedira', 'Daniel Caligiuri', 'André Hahn', 'Florian Niederlechner',
    #                     'Michael Gregoritsch'],
    #     '1. FC Köln': ['Timo Horn', 'Benno Schmitz', 'Rafael Czichos', 'Timo Hübers', 'Jannes Horn', 'Salih Özcan',
    #                    'Ellyes Skhiri', 'Ondrej Duda', 'Florian Kainz', 'Jan Thielmann', 'Anthony Modeste'],
    #     'Arminia Bielefeld': ['Stefan Ortega', 'Cedric Brunner', 'Amos Pieper', 'Joakim Nilsson', 'Anderson Lucoqui',
    #                           'Manuel Prietl', 'Sebastian Vasiliadis', 'Masaya Okugawa', 'Christian Gebauer',
    #                           'Fabian Klos', 'Janni Serra'],
    #     'VfL Bochum': ['Manuel Riemann', 'Cristian Gamboa', 'Armel Bella-Kotchap', 'Maxim Leitsch', 'Danilo Soares',
    #                    'Anthony Losilla', 'Robert Tesche', 'Gerrit Holtmann', 'Takuma Asano', 'Simon Zoller',
    #                    'Sebastian Polter'],
    #     'SpVgg Greuther Furth': ['Sascha Burchert', 'Marco Meyerhöfer', 'Nick Viergever', 'Maximilian Bauer',
    #                              'Jetro Willems', 'Sebastian Griesbeck', 'Paul Seguin', 'Jamie Leweling',
    #                              'Julian Green', 'Håvard Nielsen', 'Branimir Hrgota']
    # },
    # 'Italy': {
    #     'Juventus': ['Wojciech Szczesny', 'Danilo', 'Leonardo Bonucci', 'Matthijs de Ligt', 'Alex Sandro',
    #                  'Weston McKennie', 'Arthur', 'Adrien Rabiot', 'Paulo Dybala', 'Alvaro Morata', 'Federico Chiesa'],
    #     'AC Milan': ['Mike Maignan', 'Davide Calabria', 'Fikayo Tomori', 'Alessio Romagnoli', 'Theo Hernandez',
    #                  'Franck Kessie', 'Ismael Bennacer', 'Sandro Tonali', 'Brahim Diaz', 'Zlatan Ibrahimovic',
    #                  'Olivier Giroud'],
    #     'Inter Milan': ['Samir Handanovic', 'Milan Skriniar', 'Stefan de Vrij', 'Alessandro Bastoni', 'Denzel Dumfries',
    #                     'Nicolo Barella', 'Marcelo Brozovic', 'Hakan Calhanoglu', 'Ivan Perisic', 'Lautaro Martinez',
    #                     'Edin Dzeko'],
    #     'AS Roma': ['Rui Patricio', 'Rick Karsdorp', 'Gianluca Mancini', 'Chris Smalling', 'Matias Vina',
    #                 'Bryan Cristante', 'Jordan Veretout', 'Lorenzo Pellegrini', 'Nicolo Zaniolo', 'Henrikh Mkhitaryan',
    #                 'Tammy Abraham'],
    #     'Napoli': ['David Ospina', 'Giovanni Di Lorenzo', 'Kalidou Koulibaly', 'Amir Rrahmani', 'Mario Rui',
    #                'Fabian Ruiz', 'Piotr Zielinski', 'Eljif Elmas', 'Hirving Lozano', 'Victor Osimhen',
    #                'Lorenzo Insigne'],
    #     'Lazio': ['Pepe Reina', 'Manuel Lazzari', 'Francesco Acerbi', 'Luiz Felipe', 'Adam Marusic', 'Lucas Leiva',
    #               'Sergej Milinkovic-Savic', 'Luis Alberto', 'Felipe Anderson', 'Ciro Immobile', 'Pedro'],
    #     'Atalanta': ['Juan Musso', 'Rafael Toloi', 'Merih Demiral', 'Jose Luis Palomino', 'Davide Zappacosta',
    #                  'Marten de Roon', 'Remo Freuler', 'Joakim Maehle', 'Ruslan Malinovskyi', 'Duvan Zapata',
    #                  'Luis Muriel'],
    #     'Fiorentina': ['Bartlomiej Dragowski', 'Lorenzo Venuti', 'Nikola Milenkovic', 'Lucas Martinez Quarta',
    #                    'Cristiano Biraghi', 'Sofyan Amrabat', 'Gaetano Castrovilli', 'Giacomo Bonaventura',
    #                    'Jose Callejon', 'Dusan Vlahovic', 'Riccardo Sottil'],
    #     'Sassuolo': ['Andrea Consigli', 'Mert Muldur', 'Vlad Chiriches', 'Gian Marco Ferrari', 'Rogerio',
    #                  'Maxime Lopez', 'Davide Frattesi', 'Domenico Berardi', 'Filip Djuricic', 'Hamed Traore',
    #                  'Giacomo Raspadori'],
    #     'Verona': ['Ivor Pandur', 'Pawel Dawidowicz', 'Koray Gunter', 'Federico Ceccherini', 'Davide Faraoni',
    #                'Ivan Ilic', 'Adrien Tameze', 'Darko Lazovic', 'Antonin Barak', 'Gianluca Caprari',
    #                'Giovanni Simeone'],
    #     'Bologna': ['Lukasz Skorupski', 'Lorenzo De Silvestri', 'Adama Soumaoro', 'Gary Medel', 'Aaron Hickey',
    #                 'Mattias Svanberg', 'Nicolas Dominguez', 'Riccardo Orsolini', 'Roberto Soriano', 'Musa Barrow',
    #                 'Marko Arnautovic'],
    #     'Torino': ['Vanja Milinkovic-Savic', 'Wilfried Singo', 'Bremer', 'Koffi Djidji', 'Cristian Ansaldi',
    #                'Sasa Lukic', 'Tommaso Pobega', 'Karol Linetty', 'Josip Brekalo', 'Antonio Sanabria',
    #                'Andrea Belotti'],
    #     'Udinese': ['Marco Silvestri', 'Nahuel Molina', 'Rodrigo Becao', 'Bram Nuytinck', 'Jens Stryger Larsen',
    #                 'Tolgay Arslan', 'Walace', 'Roberto Pereyra', 'Gerard Deulofeu', 'Ignacio Pussetto', 'Beto'],
    #     'Sampdoria': ['Emil Audero', 'Bartosz Bereszynski', 'Omar Colley', 'Julian Chabot', 'Tommaso Augello',
    #                   'Albin Ekdal', 'Morten Thorsby', 'Antonio Candreva', 'Manolo Gabbiadini', 'Francesco Caputo',
    #                   'Fabio Quagliarella'],
    #     'Genoa': ['Salvatore Sirigu', 'Davide Biraschi', 'Andrea Masiello', 'Domenico Criscito', 'Stefano Sabelli',
    #               'Nicolo Rovella', 'Milan Badelj', 'Hernani', 'Goran Pandev', 'Caleb Ekuban', 'Mattia Destro'],
    #     'Spezia': ['Jeroen Zoet', 'Kelvin Amian', 'Petko Hristov', 'Martin Erlic', 'Simone Bastoni', 'Jacopo Sala',
    #                'Giulio Maggiore', 'Emmanuel Gyasi', 'Viktor Kovalenko', 'Daniele Verde', 'Rey Manaj'],
    #     'Cagliari': ['Alessio Cragno', 'Gabriele Zappa', 'Diego Godin', 'Andrea Carboni', 'Charalampos Lykogiannis',
    #                  'Kevin Strootman', 'Razvan Marin', 'Nahitan Nandez', 'Joao Pedro', 'Keita Balde',
    #                  'Leonardo Pavoletti'],
    #     'Venezia': ['Niki Maenpaa', 'Pasquale Mazzocchi', 'Mattia Caldara', 'Pietro Ceccaroni', 'Ridgeciano Haps',
    #                 'Luca Fiordilino', 'Gianluca Busio', 'Dor Peretz', 'Mattia Aramu', 'David Okereke', 'Thomas Henry'],
    #     'Empoli': ['Guglielmo Vicario', 'Petar Stojanovic', 'Ardian Ismajli', 'Sebastiano Luperto', 'Fabiano Parisi',
    #                'Samuele Ricci', 'Leo Stulac', 'Filippo Bandinelli', 'Nedim Bajrami', 'Patrick Cutrone',
    #                'Andrea Pinamonti'],
    #     'Salernitana': ['Vid Belec', 'Nadir Zortea', 'Stefan Strandberg', 'Norbert Gyomber', 'Wajdi Kechrida',
    #                     'Lassana Coulibaly', 'Francesco Di Tacchio', 'Grigoris Kastanos', 'Simy', 'Federico Bonazzoli',
    #                     'Milan Djuric']
    }
}

for country, teams in teams_and_players.items():
    cursor.execute('SELECT id FROM countries WHERE name = ?', (country,))
    country_id = cursor.fetchone()[0]

    for team, players in teams.items():
        cursor.execute('INSERT INTO teams (name, country_id) VALUES (?, ?)', (team, country_id))
        team_id = cursor.lastrowid

        for player, val in players.items():
            print(val, team_id)
            cursor.execute('INSERT INTO players (name, rating, picture, position, value, is_starting, team_id) VALUES (?, ?, ?, ?, ?, ?, ?)', (player, val[0], val[1], val[2], val[3], val[4], team_id))

            # else:
            #     cursor.execute('INSERT INTO players (name, rating, picture, team_id) VALUES (?, ?, ?, ?)', (player, val[0], val[1], team_id))
conn.commit()
conn.close()
